version: '3.8'

services:
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_URL: postgres://app:app@db:5432/app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER:     app
      POSTGRES_PASSWORD: app
      POSTGRES_DB:       app
    volumes:
      - /tmp/db:/var/lib/postgresql/data

