version: "3.9"

services:
  backend:
    build: ./api
    ports:
      - "5000:5000"
  frontend:
    build: ./sys-stats
    ports:
      - "3000:3000"
    volumes:
      - ./sys-stats/build/:/app/build/

