version: '3.7'
services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER:     shapr
      POSTGRES_PASSWORD: shapr
      POSTGRES_DB:       shapr
    volumes:
      - ./tmp/db:/var/lib/postgres
  web:
    tty: true
    stdin_open: true
    build: .
    environment:
      DATABASE_URL: postgres://shapr:shapr@database/shapr
    command: sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - database
